-- 결제 테이블
CREATE TABLE PAYMENT
(
    PAYMENT_ID         VARCHAR(100)                        NOT NULL COMMENT '결제 ID',
    TRANSACTION_ID     VARCHAR(100) NULL COMMENT 'PG사 거래 번호',
    PAYMENT_NO         VARCHAR(100)                        NOT NULL COMMENT '결제 번호',
    AMOUNT             BIGINT                              NOT NULL COMMENT '금액',
    ORDER_NO           VARCHAR(100)                        NOT NULL COMMENT '주문 번호',
    PG_PROVIDER_TYPE   VARCHAR(50)                         NOT NULL COMMENT '결제 대행사 타입',
    PAYMENT_STATUS     VARCHAR(50)                         NOT NULL COMMENT '결제 상태',
    PAYMENT_METHOD     VARCHAR(20) NULL COMMENT '결제 수단',
    APPROVAL_DATE_TIME TIMESTAMP NULL COMMENT '결제 승인 일시',
    BUYER_PHONE        VARCHAR(20) NULL COMMENT '구매자 휴대폰 번호',
    BUYER_EMAIL        VARCHAR(50) NULL COMMENT '구매자 이메일 주소',
    CREATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '데이터 생성 시각',
    UPDATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '데이터 수정 시각',
    PRIMARY KEY (PAYMENT_ID)
) COMMENT '결제';

-- 이니시스 결제 테이블
CREATE TABLE PAYMENT_INICIS
(
    PAYMENT_ID         VARCHAR(100)                        NOT NULL COMMENT '결제 ID',
    AUTH_TOKEN         TEXT                                NOT NULL COMMENT '승인 요청 검증 토큰',
    IDC_CODE           VARCHAR(20)                         NOT NULL COMMENT 'IDC 센터 코드',
    APPROVAL_URL       VARCHAR(255)                        NOT NULL COMMENT '승인 요청 URL',
    NETWORK_CANCEL_URL VARCHAR(255)                        NOT NULL COMMENT '망취소 요청 URL',
    CREATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '데이터 생성 시각',
    UPDATED_AT         TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '데이터 수정 시각',
    PRIMARY KEY (PAYMENT_ID),
    FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT (PAYMENT_ID)
) COMMENT '이니시스 결제';

-- 결제 취소 테이블
CREATE TABLE PAYMENT_CANCEL
(
    PAYMENT_CANCEL_ID     BIGINT AUTO_INCREMENT COMMENT '결제 취소 ID',
    PAYMENT_ID            VARCHAR(100)                        NOT NULL COMMENT '결제 ID',
    CANCEL_TRANSACTION_ID VARCHAR(100) NULL COMMENT '취소 PG 거래 번호',
    PAYMENT_CANCEL_TYPE   VARCHAR(50)                         NOT NULL COMMENT '결제 취소 타입',
    CANCEL_AMOUNT         BIGINT                              NOT NULL COMMENT '취소 금액',
    REASON                VARCHAR(255) NULL COMMENT '취소 사유',
    CREATED_AT            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '데이터 생성 시각',
    UPDATED_AT            TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '데이터 수정 시각',
    PRIMARY KEY (PAYMENT_CANCEL_ID),
    FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT (PAYMENT_ID)
) COMMENT '결제 취소';

-- 결제 로그 테이블
CREATE TABLE PAYMENT_LOG
(
    PAYMENT_LOG_ID BIGINT AUTO_INCREMENT NOT NULL COMMENT '로그 ID',
    PAYMENT_ID     VARCHAR(100)                              NOT NULL COMMENT '결제 ID',
    PAYMENT_STATUS VARCHAR(50)                               NOT NULL COMMENT '결제 상태',
    MESSAGE        TEXT NULL COMMENT '메시지',
    CREATED_AT     TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL COMMENT '데이터 생성 시각',
    UPDATED_AT     TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) NOT NULL COMMENT '데이터 수정 시각',
    PRIMARY KEY (PAYMENT_LOG_ID),
    FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT (PAYMENT_ID)
) COMMENT '결제 로그';