# local 용 Spring Profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:25432/user
    username: user
    password: welcome
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: '"user"'
    show-sql: true
  flyway:
    enabled: true
    validate-migration-naming: true
    schemas: user
    default-schema: user
server:
  port: 3004
feign:
  api:
    auth-url: http://localhost:3001

logging:
  level:
    root: info
    dev.montyoh: debug