# prod 용 Spring Profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: user
  flyway:
    enabled: true
    validate-migration-naming: true
    schemas: user
    default-schema: user
server:
  port: 3004

feign:
  api:
    auth-url: ${AUTH_URL}

logging:
  level:
    root: info
