whitelist:
  urls:
    # Auth
    - "/api/auth/v1/token"

    # User
    - "/api/user/v1/users/login"

    # Health Check
    - "/api/healthcheck"
    - "/api/auth/v1/monitor/healthcheck"
    - "/api/content/v1/monitor/healthcheck"
    - "/api/payment/v1/monitor/healthcheck"
    - "/api/user/v1/monitor/healthcheck"

    # 결제 테스트로 인한 임시 처리
    - "/api/payment/**"