#   JWT
service.jwt.secret-key=OWfRJ4qOlB6S3eRbQQ60O+Dkh1g/mcH3qn1USEhL1hMm3UdXLVHzwnauXqXepWx2v2zh90gJLRR9fKJgPFT1LQ==
service.jwt.mcp-secret-key=PByEX8DJoiGvW67S6UMyBIo4+W7qGLSb2USUQEeQRY5hoMpyy0hKmT+/w7YyRBGP1RnPs7gcfOf9a4gBbTOMgw==

#   Mapping URL
mapping.url.content=http://localhost:3002
mapping.url.payment=http://localhost:3003
mapping.url.user=http://localhost:3004
mapping.url.vikunja-mcp=http://localhost:8000