#   JWT
service.jwt.secret-key=${JWT_SECRET_KEY}
service.jwt.mcp-secret-key=${MCP_JWT_SECRET_KEY}

#   Mapping URL
mapping.url.auth=http://backend-api-server-auth
mapping.url.content=http://backend-api-server-content:3002
mapping.url.payment=http://backend-api-server-payment
mapping.url.user=http://backend-api-server-user
mapping.url.vikunja-mcp=http://vikunja-mcp