#   JWT
service.jwt.secret-key=OWfRJ4qOlB6S3eRbQQ60O+Dkh1g/mcH3qn1USEhL1hMm3UdXLVHzwnauXqXepWx2v2zh90gJLRR9fKJgPFT1LQ==
service.jwt.mcp-secret-key=PByEX8DJoiGvW67S6UMyBIo4+W7qGLSb2USUQEeQRY5hoMpyy0hKmT+/w7YyRBGP1RnPs7gcfOf9a4gBbTOMgw==
service.jwt.valid-time.access=1
service.jwt.valid-time.refresh=43200
#   Redis
redis.refresh-token.ttl=10