name: Manual Redeploy (master)

on:
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ gateway, payment ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Check out Secrets store
        uses: actions/checkout@v5
        with:
          repository: 'dev-montyoh/secrets-store'
          token: ${{ secrets.SECRETS_STORE_ACCESS_TOKEN }}
          path: secrets-store

      - name: Load secrets
        uses: ./secrets-store/.github/actions/load-secrets
        with:
          SECRETS_STORE_ACCESS_TOKEN: ${{ secrets.SECRETS_STORE_ACCESS_TOKEN }}

      - name: Setup JDK 19
        uses: actions/setup-java@v5
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Setup Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Service ${{ matrix.service }} Gradle build jar
        run: |
          cd ${{ matrix.service }}
          chmod +x ./gradlew
          ./gradlew bootJar

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ env.DOCKER_REGISTRY_ACCESS_TOKEN }}

      - name: Service ${{ matrix.service }} Build and Push ARM64 Docker Image
        run: |
          cd .github/docker
          docker buildx build \
            --platform linux/arm64 \
            -f Dockerfile \
            -t ghcr.io/${{ github.repository_owner }}/backend-api-server-${{ matrix.service }}:latest \
            -t ghcr.io/${{ github.repository_owner }}/backend-api-server-${{ matrix.service }}:${{ github.run_number }} \
            --build-arg SERVICE_NAME=${{ matrix.service }} \
            --build-arg PROFILE=prod \
            --push \
            ../../

      - name: ENV to JSON
        id: set_env_json
        run: |
          echo "ENV_VARS_JSON=$(echo '${{ toJSON(env) }}' | jq -c '.')" >> $GITHUB_OUTPUT

      - name: Deploy
        uses: appleboy/ssh-action@v1
        env:
          DOCKER_REGISTRY_ACCESS_TOKEN: ${{ env.DOCKER_REGISTRY_ACCESS_TOKEN }}
          DOCKER_REGISTRY_USERNAME: ${{ github.repository_owner }}
          TARGET_SERVICE: ${{ matrix.service }}
        with:
          host: ssh.montyoh.dev
          username: ubuntu
          key_path: ./secrets-store/key/ec2-ssh-key
          envs: DOCKER_REGISTRY_ACCESS_TOKEN,DOCKER_REGISTRY_USERNAME,TARGET_SERVICE
          script: |
            ENV_JSON='${{ steps.set_env_json.outputs.ENV_VARS_JSON }}'
            eval $(echo "$ENV_JSON" | jq -r '
              to_entries[]
              | select((.key | startswith("GITHUB_") | not) and (.key | startswith("RUNNER_") | not))
              | "export \(.key)=\"\(.value)\";"
            ' | tr -d '\n')

            docker ps -q --filter "name=backend-api-server-$TARGET_SERVICE" | xargs -r docker stop
            docker ps -a -q --filter "name=backend-api-server-$TARGET_SERVICE" | xargs -r docker rm
            docker images -q ghcr.io/$DOCKER_REGISTRY_USERNAME/backend-api-server-$TARGET_SERVICE:latest | xargs -r docker rmi -f

            echo "$DOCKER_REGISTRY_ACCESS_TOKEN" | docker login ghcr.io -u $DOCKER_REGISTRY_USERNAME --password-stdin
            cd /home/ubuntu/app
            curl -L -o docker-compose.yml https://raw.githubusercontent.com/$DOCKER_REGISTRY_USERNAME/iac-terraform/refs/heads/master/docker-compose.yml
            docker-compose pull backend-api-server-$TARGET_SERVICE
            docker-compose up -d backend-api-server-$TARGET_SERVICE
