name: pull-request-master-stack.yml

on:
  pull_request:
    branches:
      - master

jobs:
  pull_request_master:
    strategy:
      matrix:
        service: [ gateway, payment, auth, user ]
    uses: ./.github/workflows/pull-request-master-module.yml
    with:
      service: ${{ matrix.service }}
